services:
  contained-pods:
    image: localhost/contained-pods:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - USER_PASSWORD=${USER_PASSWORD}
