services:
  contained-pods:
    image: localhost/contained-pods:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        - PODUSER_PASSWORD=${PODUSER_PASSWORD}
