services:
  contained-dockers:
    image: localhost/contained-dockers:latest
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - user_password

secrets:
  user_password:
    file: ./my_password.txt
