services:
  contained:
    container_name: ${VARIANT}-contained
    image: localhost/${VARIANT}-contained:latest
    userns_mode: keep-id
    build:
      context: ../..
      dockerfile: dockers/${VARIANT}/Dockerfile
      network: host            ## this host network link is only for build time installs
      args:
        - PROXY_HOSTNAME=${VARIANT}-contained-proxy
    # ports:
    #   - "2222:22" # Allows SSH from host
    volumes:
      - ./projects:/home/poduser/projects:rw
      - ../../config:/home/poduser/config:rw
    networks:
      - contained-net
    environment:
      - PROXY_NAME=${VARIANT}-contained-proxy
      - http_proxy=http://${VARIANT}-contained-proxy:3128
      - https_proxy=http://${VARIANT}-contained-proxy:3128
      - no_proxy=localhost,127.0.0.1
    restart: unless-stopped
    depends_on:
      - contained-proxy

  contained-proxy:
    image: localhost/${VARIANT}-contained-proxy:latest
    build:
      context: ../../proxy
      dockerfile: Dockerfile
      network: host          ## this host network link is only for build time installs
    container_name: ${VARIANT}-contained-proxy
    networks:
      - contained-net
      - internet-net
    volumes:
      - ./proxy/squid.conf:/etc/squid/squid.conf:ro
      - ./proxy/logs:/var/log/proxy-logs:rw
    restart: unless-stopped

networks:
  contained-net:
    name: ${VARIANT}-contained-net
    driver: bridge
    internal: true
    labels:
      com.docker.compose.network: ${VARIANT}-contained-net
  internet-net:
    external: true
